

-- 테이블 생성 기본값
CREATE TABLE Board
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
    body VARCHAR(2047) NOT NULL,
    memberID VARCHAR(255) NOT NULL,
	inserted TIMESTAMP DEFAULT now()
);

DESC Board;
SELECT * FROM Board;